version: '3'

dotenv: ['.env']

vars:
  TERMUX: '{{and .PREFIX (contains "com.termux" .PREFIX)}}'
  TODAY: '{{now | date "2006-01-02"}}'
  HUGO: '{{default "hugo" .HUGO}}'

tasks:
  serve:
    desc: Runs hugo serve, all posts visible.
    cmds:
      - |
        {{.HUGO}} serve -D -E -F {{if .TERMUX}}--noBuildLock{{end}} --bind=0.0.0.0 --baseURL=http://0.0.0.0:1313

  build:
    desc: Create a production build of the site in ./public.
    cmds:
      - |
        {{.HUGO}} --minify {{if .TERMUX}}--noBuildLock{{end}}

  to-bundle:
    desc: Turns a single page (page.md) into a bundle (page/index.md).
    vars:
      PAGE: 'content/{{trimPrefix "content/" .CLI_ARGS}}'
      DIR: '{{trimSuffix ".md" .PAGE}}'
    preconditions:
      - test -f "{{.PAGE}}"
      - sh: "[ ! -d \"{{.DIR}}\" ]"
    cmds:
      - |
        mkdir "{{.DIR}}"
        mv "{{.PAGE}}" "{{.DIR}}/index.md"

  to-single:
    desc: Turns a bundle (page/index.md) into a single page (page.md).
    vars:
      BUNDLE: 'content/{{trimPrefix "content/" (trimSuffix "/" .CLI_ARGS)}}'
      PAGE: '{{.BUNDLE}}.md'
    preconditions:
      - test -d "{{.BUNDLE}}"
      - test -f "{{.BUNDLE}}/index.md"
      - sh: "[ ! -f \"{{.BUNDLE}}.md\" ]"
      - sh: "[ -n $(find \"{{.BUNDLE}}\" -mindepth 1 -maxdepth 1 | grep -v index.md) ]"
    cmds:
      - |
        mv "{{.BUNDLE}}/index.md" "{{.PAGE}}"
        rm -r "{{.BUNDLE}}"

  update-mods:
    desc: Updates all submodules.
    cmds:
      - git submodule update --remote --merge
      - cd themes/gochowdown && git pull origin master
